// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { MatchCounter } from "./tables/MatchCounter.sol";
import { Match, MatchData } from "./tables/Match.sol";
import { Player } from "./tables/Player.sol";
import { MatchHasPlayer } from "./tables/MatchHasPlayer.sol";
import { PlayerReady } from "./tables/PlayerReady.sol";
import { Tile, TileData } from "./tables/Tile.sol";
