// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IMainSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMainSystem {
  function createMatch(
    uint8 sizeX,
    uint8 sizeY,
    uint8 maxPlayers,
    uint32 cityDensity,
    uint32 mountainDensity,
    uint32 armyGrowth
  ) external;

  function changeMatchConfig(
    uint256 matchId,
    uint8 sizeX,
    uint8 sizeY,
    uint8 maxPlayers,
    uint32 cityDensity,
    uint32 mountainDensity,
    uint32 armyGrowth
  ) external;

  function joinMatch(uint256 matchId) external;

  function removePlayer(uint256 matchId, address playerId) external;

  function startMatch() external;
}
